baseURL = "http://example.org/"
languageCode = "en-us"
title = "Rendering Portfolio"

[security.html]
  allowInlineScripts = true  # Allows <script> tags with inline JS
  allowInlineStyles = true   # Optional: if using inline styles